version: '3'

services:
  web:
    restart: always
    build: ./restapi
    ports:
      - 5001:80
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./:/usr/src/app
    env_file: .env
    environment:
      DEBUG: 'true'
    command: python restapi/manage.py runserver 0.0.0.0:80


  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: "redis:alpine"


  celery:
    restart: always
    build: ./restapi
    env_file: .env
    command: celery -A config worker -l info
    volumes:
      - celerydata:/usr/src/app/
    links:
        - redis:redis
    depends_on:
      - redis
      - postgres
      
     
volumes:
  celerydata:
  pgdata:
  redisdata:
  